version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: python-app
    environment:
      - ENVIRONMENT=DEV
      - HOST=localhost
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

    depends_on:
      - redis
    ports:
      - "8000:8000"
  
  redis:
    image: redis:latest
    expose:
    - 6379
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data

volumes:
  redis-data:
    driver: local