pipeline {
    agent any
    stages {
        stage('test') {
            steps {
               sh "python3 tests/test.py"
            }
        }

        // stage('Build & Deploy') {
        //     steps {
        //         sh "docker-compose up "
        //     }
        // }
    }
}