pipeline {
    agent any
    stages {
        stage('test') {
            steps {
               sh "python3 challenge_1/PythonApp/tests/test.py"
            }
        }

        stage('Build & Deploy') {
            steps {
                sh "docker-compose up "
            }
        }
    }
}