pipeline {
    agent any
    stages {
        stage('test') {
            steps {
               sh "python3 challenge_1/PythonApp/tests/test.py"
            }
        }

        stage('Build & Deploy') {
            steps {
                sh 'pwd'
                sh "docker-compose -d -f challenge_1/docker-compose.yaml up"
            }
        }
    }
}