---
- name: run kubectl
  hosts: localhost
  tasks:
    - name: Find out playbook's path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout_lines

    - name: apply configmap
      shell: /usr/local/bin/kubectl/kubectl create configmap -n {{db_env}} mysql-config --from-literal=USERNAME={{mysql_username}} --from-literal=PASSWORD={{mysql_password}} --from-literal=DATABASE={{db_name}} -o yaml --dry-run=client | /usr/local/bin/kubectl/kubectl apply -f -
      register: apply_configmap_output
    - debug: var=apply_configmap_output.stdout_lines

    - name: create docker registry secret
      shell: /usr/local/bin/kubectl/kubectl create secret docker-registry nexus_registry --docker-server=http://35.224.32.63:30003 --docker-username={{REGISTRY_USER}}  --docker-password={{REGISTRY_PWD}}' -o yaml --dry-run=client | /usr/local/bin/kubectl/kubectl apply -f -
      register: apply_docker_registry_secret_output
    - debug: var=apply_docker_registry_secret_output.stdout_lines

    - name: apply deployment
      shell: /usr/local/bin/kubectl/kubectl apply -n {{db_env}} -f app_deployment.yaml -f app_service.yaml
      register: apply_deployment_output
    - debug: var=apply_deployment_output.stdout_lines
