---
- name: Install nginx
  remote_user: ec2-user
  hosts: EC2
  become: true

  tasks:
  - name: Upgrade all packages
    yum:
      name=*
      state=latest

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
