pipeline {
    agent any
    stages {
        stage('Cloning') {
            steps {
              sh "rm -rf ./jenkins_nodejs_example"
               sh "git clone https://github.com/atefhares/jenkins_nodejs_example ./jenkins_nodejs_example"
               sh "cd ./jenkins_nodejs_example && git checkout $commit_id"
            }
        }

        stage('Building') {
            steps {
                sh "docker build --tag=jenkins_nodejs_example ./jenkins_nodejs_example"
            }
        }

        stage('Pushing') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker_id', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]) {
                  sh 'docker login -u=$DOCKER_REGISTRY_USER -p=$DOCKER_REGISTRY_PWD'
                  sh 'docker tag jenkins_nodejs_example atefhares/jenkins_nodejs_example:latest'
                  sh "docker push atefhares/jenkins_nodejs_example"
                }
            } 
        }
    }
}