apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  template:
    metadata:
      labels:
        tag: nodejsapp
    spec:
      containers:
        - name: nodejsapp
          image: atefhares/jenkins_nodejs_example:latest
          ports:
            - containerPort: 3000
          env:
            - name: HOST
              value: "mysql-service"
            - name: USERNAME
              value: "X"
            - name: PASSWORD
              value: "X"
            - name: DATABASE
              value: "X"
  replicas: 1
  selector:
    matchLabels:
      tag: nodejsapp
