---
- name: run kubectl
  hosts: localhost
  tasks:

  - name: Find out playbook's path
    shell: pwd
    register: playbook_path_output
  - debug: var=playbook_path_output.stdout

  - name: apply configmap
    shell: |
      /usr/local/bin/kubectl/kubectl create configmap -n {{db_env}} mysql-config --from-literal=USERNAME={{mysql_username}} --from-literal=PASSWORD={{mysql_password}} --from-literal=DATABASE={{db_name}} -o yaml --dry-run=client | /usr/local/bin/kubectl/kubectl apply -f -

  - name: apply deployment
    shell: |
      "/usr/local/bin/kubectl/kubectl apply -n {{db_env}} -f app_deployment.yaml -f app_service.yaml"
