pipeline {
    agent any
    stages {
        stage('Deploying') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                withCredentials([usernamePassword(credentialsId: 'mysql_data', passwordVariable: 'mysql_password', usernameVariable: 'mysql_username')]) {
                    sh 'ansible-playbook --connection=local --inventory 127.0.0.1 challenge_6/cd/deploy.yml --extra-vars "mysql_username=${mysql_username} mysql_password=${mysql_password} db_name=${db_name} db_env=${db_env}"'
                //   sh '/usr/local/bin/kubectl/kubectl create configmap -n $db_env mysql-config --from-literal=USERNAME=$mysql_username --from-literal=PASSWORD=$mysql_password --from-literal=DATABASE=$db_name -o yaml --dry-run=client | /usr/local/bin/kubectl/kubectl apply -f -'
                }
                // sh "/usr/local/bin/kubectl/kubectl apply -n $db_env -f challenge_6/cd/app_deployment.yaml -f challenge_6/cd/app_service.yaml"
            } 
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}