- name: Install nginx
  yum:
    name: nginx
    state: absent

- name: Start NGiNX
  service:
    name: nginx
    state: started
    enabled: true

- name: insert index.html
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html